### ISSUE TITLE
pre bumped package.json: required 'files'

### ISSUE THREAD

**Issue by tiendq** [bumped/bumped#153]
When I ran `bumped release 1.0.0` I got this error `pre bumped package.json: required 'files'`.

The problem is I don't know what is `files` field for and why is it required?

**Comment by Kikobeats** [comment]
Probably you are using [`bumped-finepack`](https://www.npmjs.com/package/bumped-finepack) who lints your `package.json` every time you perform the action of creating a new build.

[finepack](https://www.npmjs.com/package/finepack) is saying you that your `files` field at `package.json` is empty, being a good practice to declare there the files of your module: https://docs.npmjs.com/files/package.json#files

Here an [example](https://github.com/bumped/bumped/blob/master/package.json#L64) how it looks like.

**Comment by Kikobeats** [comment]
I close this but please feel free to reply 🙂

**Comment by tiendq** [comment]
I also found it was `finepack` issue, and I don't agree using `files` is a best practice, it's optional, npm doesn't list it as recommended. And I have never used it even in packages.

I see finepack is useless so I just don't use it. Thanks.

**Comment by Kikobeats** [comment]
just `finepack --no-validate` avoids `files` validation
