### ISSUE TITLE
Fail on missing version in bower.json

### ISSUE THREAD

**Issue by nmaggioni** [bumped/bumped#16]
Bumped fails if the _version_ field is not present in the `bower.json` file, but [as per the official specs](https://github.com/bower/spec/blob/master/json.md#version) that field is deprecated. Shouldn't this exception be handled somehow?

`$ bumped init`

```
bumped Detected package.json in the directory.
bumped Detected bower.json in the directory.
bumped File package.json has been added.
bumped File bower.json has been added.
/home/nmaggioni/.npm-packages/lib/node_modules/bumped/node_modules/semver/semver.js:279
    throw new TypeError('Invalid Version: ' + version);
    ^

TypeError: Invalid Version: undefined
  at new SemVer (/home/nmaggioni/.npm-packages/lib/node_modules/bumped/node_modules/semver/semver.js:279:11)
  at compare (/home/nmaggioni/.npm-packages/lib/node_modules/bumped/node_modules/semver/semver.js:566:10)
  at Function.gt (/home/nmaggioni/.npm-packages/lib/node_modules/bumped/node_modules/semver/semver.js:595:10)
  at /home/nmaggioni/.npm-packages/lib/node_modules/bumped/lib/Bumped.semver.coffee:31:31
  at /home/nmaggioni/.npm-packages/lib/node_modules/bumped/node_modules/async/lib/async.js:375:13
  at iterate (/home/nmaggioni/.npm-packages/lib/node_modules/bumped/node_modules/async/lib/async.js:262:13)
  at Object.async.forEachOfSeries.async.eachOfSeries (/home/nmaggioni/.npm-packages/lib/node_modules/bumped/node_modules/async/lib/async.js:281:9)
  at Object.async.inject.async.foldl.async.reduce (/home/nmaggioni/.npm-packages/lib/node_modules/bumped/node_modules/async/lib/async.js:374:15)
  at module.exports.Semver.max (/home/nmaggioni/.npm-packages/lib/node_modules/bumped/lib/Bumped.semver.coffee:30:11)
  at /home/nmaggioni/.npm-packages/lib/node_modules/bumped/node_modules/async/lib/async.js:1149:20
  at /home/nmaggioni/.npm-packages/lib/node_modules/bumped/node_modules/async/lib/async.js:375:13
  at Immediate.iterate [as _onImmediate] (/home/nmaggioni/.npm-packages/lib/node_modules/bumped/node_modules/async/lib/async.js:262:13)
  at tryOnImmediate (timers.js:534:15)
  at processImmediate [as _immediateCallback] (timers.js:514:5)
```

**Comment by Kikobeats** [comment]
Just create a file called server.json with version key and add it to bumped

**Comment by Kikobeats** [comment]
I can add this case. What do you expect for the new behavior?

**Comment by nmaggioni** [comment]
@Kikobeats I'd rather avoid adding fields/files around, as most of my configurations reside in npm's `package.json`.
It may be nice if missing _version_ fields could be ignored, maybe with a CLI switch if hardcoding this feature isn't an option. What do you reckon?

**Comment by Kikobeats** [comment]
@nmaggioni I'm agree, but the problem that is necessary add a special behavior just for bower.json files... I mean, the system has been created to work with whatever .json configfile. The only necessary requisite is have in the JSON a version field.

I'm thinking implement something like:

```
files: [
  'package.json' # First file need to have 'version' key as required.
  'bower.json'    # Optional 'version' key for rest of files. library does best effort.
]
```

What do you think?

**Comment by nmaggioni** [comment]
I agree on your idea - my example was about bower, but in fact it extends to every added file.

Regarding the first file being "prioritized": I'd suggest throwing an error if the _version_ field is **not found in any files**, and a warning whenever an analyzed file does not contain it.
This way everyone who didn't set it's main package manager as the first file won't be penalized, and there'll also be less documentation to write as the change won't impact the user's workflow directly.

**Comment by Kikobeats** [comment]
Good point!
I suppose that you are not acquainted with the code, but PR is welcome. I can write this feature but need a window time for do that :-)

**Comment by nmaggioni** [comment]
I was looking at the code right now :)
My CoffeeScript skills are okay, but the code's structure is giving me a bit of a headache.

**Comment by Kikobeats** [comment]
I'm going to work on this for release stable version soon! 💃

**Comment by Kikobeats** [comment]
Working on this, I hope ship it this weekend!
