### ISSUE TITLE
Release unstable versions

### ISSUE THREAD

**Issue by dennervidal** [bumped/bumped#182]
Hello,

There is a way to release unstable builds for staging?

The releases will be in format major.minor.patch-tag or major.minor.patch-tag.version. For example:
- 1.0.0-beta.0

Thanks for helping.

**Comment by Kikobeats** [comment]
hmm what about `bumped release premajor` ?

**Comment by dennervidal** [comment]
It seems that will work. Just a question: bumped is able to handle tags inside the version?

**Comment by Kikobeats** [comment]
Bumped just increment the version, but you can perform any pre/post step (like npm publish)

Check this example

https://github.com/Kikobeats/is-url-http/blob/master/.bumpedrc
