### ISSUE TITLE
Why .bumpedrc is not a standard JSON?

### ISSUE THREAD

**Issue by edouard-lopez** [bumped/bumped#48]

**Comment by Kikobeats** [comment]
You can use a JSON as well!

However I think that CSON is more useful for this case because it allows you create a config file more readable (because it avoids brackets)

**Comment by fetchTe** [comment]
I agree on the brackets, but CSON is not the best option. What about migrating to YAML via [js-yam](https://github.com/nodeca/js-yaml)? I would do it myself, but I don't make coffee.

**Comment by Kikobeats** [comment]
Could be possible, I think that would be easy support JSON, CSON and YAML

**Comment by edouard-lopez** [comment]
I will stick to `JSON` as I don't think the trade-off is worth it. Indeed all examples in the docs use **simple commands**. And if you are in the situation where you write a multilines command, then better write a shell script, test it and call it like `./my-command.sh`

### For reference

I've no idea how to convert [my `.bumpedrc` config](https://github.com/Coaxis-ASP/opt/blob/b31327f159af8d73468fdbd9a47d8a734fb81874/daemon/frontend/.bumpedrc) from `CSON` to `JSON`. 

## `.bumpedrc`

```
files: [
    "package.json"
]
plugins:
    prerelease: {}

    postrelease:
        'Commiting new version':
            plugin: 'bumped-terminal'
            command: 'git add package.json && git commit --amend --no-edit'

        'Tagging locally':
            plugin: 'bumped-terminal'
            command: 'git tag v$newVersion'
```

Could you show me what's the `JSON` equivalent?

**Comment by edouard-lopez** [comment]
Ok might be more trivial than I tought to convert back (not-tested yet):

```
{
    "files": [
        "package.json"
    ],
    "plugins": {
        "prerelease": {},
        "postrelease": {
            "Commiting new version": {
                "plugin": "bumped-terminal",
                "command": "git add package.json && git commit --amend --no-edit"
            },
            "Tagging locally": {
                "plugin": "bumped-terminal",
                "command": "git tag v$newVersion"
            }
        }
    }
}
```

**Comment by Kikobeats** [comment]
@edouard-lopez I think so!

BTW YAML looks a good approach, any one can investigate about this integration and write a PR?

**Comment by edouard-lopez** [comment]
bump.

Doesn't 06f680c9e6 fix this issue ?

**Comment by Kikobeats** [comment]
I'm not sure to understand you. Last bumped version support JSON/CSON/YAML config file.

**Comment by edouard-lopez** [comment]
oh my bad I didn't saw it was already closed :/
