### ISSUE TITLE
Support YAML for config files

### ISSUE THREAD

**Issue by Kikobeats** [bumped/bumped#51]
Related with https://github.com/bumped/bumped/issues/48#issuecomment-248466556

**Comment by Kikobeats** [comment]
About that, I didn't found a immediate solution.

Because currently `.bumpedrc` haven't extension, we can build a tiny module that do try/catch for detect the file format. For example:
- If the file starts with `{`, then the format is JSON.
- try to load with CSON dep; if failed, then is YAML.

What do you think? .cc @edouard-lopez @artisin

**Comment by edouard-lopez** [comment]
Something like:
- [How to check if a string is a valid JSON string in JavaScript without using Try/Catch](http://stackoverflow.com/a/3710226/802365) (simplest way)
- [`is-json` module](https://www.npmjs.com/package/is-json)

**Comment by Kikobeats** [comment]
Thanks for the suggestion. Also this looks nice: https://github.com/stewartml/json-yaml

In special here: https://github.com/stewartml/json-yaml/blob/master/index.js#L6-L14

**Comment by Kikobeats** [comment]
@edouard-lopez I think that this resolve the problem: https://www.npmjs.com/package/load-config-file

**Comment by Kikobeats** [comment]
@I craft this: https://github.com/Kikobeats/parse-config-file

We can read the three format; now need to investigate about how to write the output in the same format
